Added contributing guide
jdwilkin4/fcc-forum-clone pull request #29
Opened 2022-09-26 08:53 UTC by AndreyDmitriev39r

# Description

Used file from contrast-ratio-app as a template, but added/restructured some things.
So in README we have somewhat consice contributing instructions.
In this file, there is little more detailed explanation.

Fixes #4

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [x] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked the issue to this [PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

2022-09-26 14:21 UTC, jdwilkin4 requested changes
This looks good and very detailed. It should help a lot of newcomers interested in contributing 👍 

We should add a table of contents since there are a lot of sections

2022-09-26 14:21 UTC, jdwilkin4 commented on CONTRIBUTING.md
> +Instructions about this can be found in [README](./README.md).
This section should be moved further down. It should be after the section about cloning the project. 
Also let's give them some instructions on how to install Node.js in order to use the `npm` command. 

Proposed fix: 
If you don't have Node.js installed on your computer, please read through [these instructions](https://nodejs.dev/en/).  If you are not sure if Node.js is installed, please run the `node -v` command in the command line. 

Then change to the project directory by using the `cd fcc-forum-clone` command. To install the dependencies, run the `npm install` command.

2022-09-26 14:21 UTC, jdwilkin4 commented on CONTRIBUTING.md
> +  - Once Desktop is set up, you can use it to [fork the repo](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-deskt
I don't think we need the exclamation point here since this sentence doesn't seem to indicate strong feelings or strong emphasis.

2022-09-26 14:21 UTC, jdwilkin4 commented on CONTRIBUTING.md
> +### Creating local copy of the repo (aka cloning)
```suggestion
### Creating a local copy of the repo (aka cloning)
```

2022-09-26 14:21 UTC, jdwilkin4 commented on CONTRIBUTING.md
> +### Creating new branch to start dealing with the issue
```suggestion
### Creating a new branch to start working on the issue
```

2022-09-26 14:21 UTC, jdwilkin4 commented on CONTRIBUTING.md
> +- Check out [this video](https://www.youtube.com/watch?v=RGOj5yH7evk) from freeCodeCamp youTube channel Git and GitHub basics.
```suggestion
- Check out [this video](https://www.youtube.com/watch?v=RGOj5yH7evk) from freeCodeCamp's YouTube channel on Git and GitHub basics.
```

2022-09-26 14:21 UTC, jdwilkin4 commented on CONTRIBUTING.md
> +- Don't be shy to ask us about anything related to the project and working on it! Depending on your question, use pull request threads, issue threads or the discussions!
I don't think we need either exclamation point here. Periods would work best here.

2022-09-26 15:26 UTC, AndreyDmitriev39r commented
@jdwilkin4 how do I go about table of contents? Our contributing file in the contrast-ratio-repo has table of contents, but I think it is not done by the markdown inside the file?
Table of contents should be added here? With the GitHub interface somehow?

2022-09-26 16:46 UTC, jdwilkin4 commented
@AndreyDmitriev39r 

You can create a table of contents using markdown right in the file.

> Our contributing file in the contrast-ratio-repo has table of contents

I am looking at the file here, and I don't see one here but we should probably add one there too. 
https://github.com/jdwilkin4/contrast-ratio-repo/blob/main/CONTRIBUTING.md

This is what a table of contents looks like in markdown
```md
## Table of contents

- [Documentation](#documentation)
- [Issues](#issues)
  - [Creating issues](#creating-issues)
  - [Picking up an issue to work on](#picking-up-an-issue-to-work-on)
- [Making changes](#making-changes)
  - [Installing git](#installing-git)
```
When people click on a heading in the table of contents, it will jump to that section in the file.
Here is an example of one of my open source work repos that uses it
https://github.com/thisdot/tech-podcasts

2022-09-26 16:50 UTC, jdwilkin4 commented
Also, I would suggest adding the [Markdown Preview Enhanced extension](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) to VS code.  It has a nice preview window and has a command for automatic table of contents creation.

2022-09-28 09:35 UTC, Dorfieeee commented on CONTRIBUTING.md
> +Feel free to check out [our codebase](https://github.com/jdwilkin4/fcc-forum-clone). If you think, that something could be added, fixed, or improved on, first that there is no open issue for that by
Rephrase: If you think something could be added, fixed, or improved, firstly check that there is no open issue already. You can find it in the [Issues](https://github.com/jdwilkin4/fcc-forum-clone/issues) section of this repository.

2022-10-08 17:44 UTC, sparkO7 approved these changes
The contributing file looks good. It misses a table of contents but we can add that in another issue.

2022-10-08 17:48 UTC, merged